language: cpp

matrix:
  include:
    # Ubuntu 14.04 Trusty Tahr
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    # OS X 10.11 El Capitan
    - os: osx
      osx_image: xcode7.3
      compiler: clang
    # Xcode 8 beta
    - os: osx
      osx_image: xcode8
      compiler: clang

# Linux dependencies
# See: https://github.com/gosu/gosu/wiki/Getting-Started-on-Linux
addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libpango1.0-dev
      - libgl1-mesa-dev
      - libopenal-dev
      - libsndfile1-dev
      # For Ruby
      - ruby-dev
      - rake
      # For C++
      - cmake
      # For Linux Soundtests (equivalent to xvfb)
      - alsa-base

before_install:
  # Do not use RVM - it's been a mess for compiling Gosu on macOS.
  - rvm use system

  # Print the Ruby configuration to see what's up with CXXFLAGS etc.
  - ruby -rrbconfig -e 'RbConfig::CONFIG.each { |k, v| puts [k, v].join("=") }'

  # Do some OSX-Specific preparations
  - if [ $TRAVIS_OS_NAME == osx ]; then ./.travis/before_install_osx.sh; fi

  # Dependencies for 'rake gem' (not for actually using Gosu)
  # We have to install binaries into ~ because of Apple's System Integrity Protection.
  - sudo gem install rake rake-compiler minitest --no-ri --no-rdoc -n ~

before_script:
  # Enable "dummy" devices for audio and video on Linux
  - if [ $TRAVIS_OS_NAME != osx ]; then . ./.travis/before_script_linux.sh ;fi

# Minimal git coverage (for now).
branches:
  only:
  - master
git:
  depth: 1

env:
  global:
    # 'rake gem' relies on this.
    - GOSU_RELEASE_VERSION=9.9.9
    # To silence this warning:
    # "WARNING: CocoaPods requires your terminal to be using UTF-8 encoding."
    - LANG=en_US.UTF-8

install:
  # Ruby/Gosu
  - ~/rake gem
  - sudo gem install pkg/gosu-9.9.9.gem --no-ri --no-rdoc

  # Gosu for C++ using CMake
  - "mkdir -p cmake/build &&
     cd cmake/build &&
     cmake .. &&
     make &&
     sudo make install &&
     cd ../.."

  # Do some OSX-Specific preparations
  - if [ $TRAVIS_OS_NAME == osx ]; then ./.travis/install_osx.sh ; fi

script:
  # Run Ruby/Gosu tests and compile C++ examples
  - "if [ $TRAVIS_OS_NAME == osx ];
     then
       ~/rake -rgosu test;
     else
       sg audio '~/rake -rgosu test';
     fi"
  - mkdir -p examples/build && cd examples/build && cmake .. && make
